# -*- coding: utf-8 -*-
"""createfeature.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jGXJzR5XnTL2ZYx4TpnQMbOnAD_A2wye

# <center> **Creating new features**

## **Importando arquivo**
"""
from insights.time_feature_creation.time_features import time_feature_eng

# parameters
#dataset = "DailyDelhiClimateTrain.csv" #@param {type:"string"}
dataset = "amostra.xlsx" #@param
group_col = "" #@param {type:"string",label:"coluna para o agrupamento"}

analise = time_feature_eng(file_path=dataset, resample='day')

novos_datasets = analise.grouped_tmp
novos_datasets[1][0].to_csv('amostra.csv')