name: Init Tasks - CI

on:
  push:
    branches:
    - main
    - v*-branch
    paths:
    - init-job/**
    - tasks/**
    - config.json

  pull_request:
    branches:
    - main
    - v*-branch
    paths:
    - init-job/**
    - tasks/**
    - config.json

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set output variables
      id: vars
      run: |
        VERSION=0.2.0
        if [ ${{ github.ref }} = "refs/heads/main" ]; then
          echo ::set-output name=TAG::${VERSION}-SNAPSHOT
        elif [[ ${{ github.ref }} =~ ^refs/heads/v.*-branch$ ]]; then
          echo ::set-output name=TAG::${VERSION}
        else
          echo ::set-output name=TAG::${VERSION}-${{ github.sha }}
        fi
        echo ::set-output name=BRANCH::${{ github.ref }}
        echo ::set-output name=COMMIT::${{ github.sha }}

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        coverage erase
        coverage run --branch --source=init-job -m pytest tests/test_parameters.py
        coverage xml -i

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker image 📦
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: docker.io/platiagro/tasks:${{ steps.vars.outputs.TAG }}
        build-args: |
          COMMIT=${{ steps.vars.outputs.COMMIT }}
          BRANCH=${{ steps.vars.outputs.BRANCH }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
