name: Logistic Regression

on:
  schedule:
    # Since tasks rely on the docker image "docker.io/platiagro/platiagro-notebook-image",
    # we schedule a run to check if any changes (eg. on requirements.txt) broke any tests
    # Runs once a week (on Sundays 2:30pm)
    - cron:  '30 14 * * 0'

  push:
    branches:
    - main
    - v*-branch
    paths:
    - tasks/logistic-regression/**
    - tests/datasets.py
    - tests/server.py
    - tests/test_logistic_regression.py

  pull_request:
    branches:
    - main
    - v*-branch
    paths:
    - tasks/logistic-regression/**
    - tests/datasets.py
    - tests/server.py
    - tests/test_logistic_regression.py

jobs:
  build:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image: platiagro/platiagro-notebook-image:0.3.0

    services:

      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        ports:
        - 9000:9000

    steps:
    - uses: actions/checkout@v2

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v tests/test_logistic_regression.py
      timeout-minutes: 30
      env:
        MINIO_ENDPOINT: minio:9000
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
